language: go
arch:
   - ppc64le
   - amd64

go:
    - master
    - 1.x
    - 1.12.x
    - 1.11.x
    - 1.10.x
    - 1.9.x
    - 1.8.x
    - 1.7.x
    - 1.6.x
    - 1.5.x
    - 1.4.x

jobs:
  exclude :
    - arch : ppc64le
      go : 
       - 1.4.x

script: go test -v -bench . -benchmem ./...
